<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Mentor;
use Illuminate\Database\Seeder;

class MentorSeeder extends Seeder
{
    public function run(): void
    {
        $mentors = [
            ['name'=>'Ahmad Fikri','email'=>'ahmadfikri@blitarhub.com','company'=>'Tokopedia','expertise'=>'Engineering Manager','location'=>'Jakarta, Indonesia','rating'=>4.9,'mentees'=>320,'bio'=>"Engineering Manager di Tokopedia dengan 10+ tahun pengalaman. Telah membimbing ratusan engineer dari junior hingga tech lead.\n\nMisi saya: membantu talenta Indonesia bersaing di level global.",'experience'=>[['role'=>'Engineering Manager','company'=>'Tokopedia','period'=>'2020 – Kini','desc'=>'Mengelola 3 squad (15 engineer) divisi seller platform.'],['role'=>'Senior Software Engineer','company'=>'Bukalapak','period'=>'2017 – 2020','desc'=>'Arsitektur microservices untuk sistem pembayaran.']],'education'=>[['institution'=>'Universitas Indonesia','degree'=>'S1 Ilmu Komputer','year'=>'2010–2014','gpa'=>'3.82']],'achievements'=>[['icon'=>'🏆','title'=>'Top 50 Tech Leaders Indonesia','issuer'=>'Tech in Asia','year'=>'2024'],['icon'=>'📜','title'=>'Google Cloud Professional Architect','issuer'=>'Google','year'=>'2022']],'programs'=>[['title'=>'1-on-1 Career Coaching','price'=>'Rp 250.000','desc'=>'60 menit: CV review, interview prep, career path di dunia tech.','duration'=>'60 menit','format'=>'Video Call','enrolled'=>185],['title'=>'System Design Mastery','price'=>'Rp 500.000','desc'=>'Rancang sistem untuk jutaan pengguna. Hands-on whiteboard session.','duration'=>'90 menit','format'=>'Video Call + Whiteboard','enrolled'=>92],['title'=>'Engineering Leadership Bootcamp','price'=>'Rp 1.500.000','desc'=>'4 sesi: people management, sprint planning, stakeholder communication.','duration'=>'4x 90 menit','format'=>'Cohort-based','enrolled'=>43]],'testimonials'=>[['name'=>'Rina Susanti','role'=>'Software Engineer at Shopee','stars'=>5,'comment'=>'Dapat offer Shopee dengan gaji 2x lipat setelah sesi career coaching!'],['name'=>'Hendra W.','role'=>'Tech Lead at Gojek','stars'=>5,'comment'=>'System Design Mastery benar-benar membuka wawasan.'],['name'=>'Dewi Anggraini','role'=>'Engineering Manager at Blibli','stars'=>5,'comment'=>'Leadership Bootcamp sangat membantu transisi dari IC ke manager.']]],
            ['name'=>'Jessica Wongso','email'=>'jessica@blitarhub.com','company'=>'Shopee','expertise'=>'VP of Product','location'=>'Singapore','rating'=>5.0,'mentees'=>150,'bio'=>'VP of Product di Shopee. 8 tahun di product management. Membangun product team dari nol di dua unicorn.','experience'=>[['role'=>'VP of Product','company'=>'Shopee','period'=>'2022 – Kini','desc'=>'Memimpin product strategy untuk Shopee Mall.'],['role'=>'Head of Product','company'=>'OVO','period'=>'2019 – 2022','desc'=>'Membangun product team dari 3 menjadi 25 orang.']],'education'=>[['institution'=>'NUS Singapore','degree'=>'MBA','year'=>'2017–2019','gpa'=>'3.9']],'achievements'=>[['icon'=>'🏆','title'=>'Forbes 30 Under 30 SEA','issuer'=>'Forbes','year'=>'2021']],'programs'=>[['title'=>'Product Management 101','price'=>'Gratis','desc'=>'Perkenalan PM untuk fresh graduate.','duration'=>'45 menit','format'=>'Video Call','enrolled'=>120],['title'=>'PM Career Accelerator','price'=>'Rp 750.000','desc'=>'3 sesi intensif: mock interview, portfolio review, career path.','duration'=>'3x 60 menit','format'=>'Cohort-based','enrolled'=>30]],'testimonials'=>[['name'=>'Anisa Larasati','role'=>'Product Manager at Tokopedia','stars'=>5,'comment'=>'Jessica sangat inspiring! Materi PM-nya sangat relevan.'],['name'=>'Bayu P.','role'=>'APM at Gojek','stars'=>5,'comment'=>'Berhasil pivot dari engineering ke PM setelah ikut program ini.']]],
            ['name'=>'Reza Rahardian','email'=>'reza@blitarhub.com','company'=>'Investree','expertise'=>'CTO & Startup Advisor','location'=>'Jakarta, Indonesia','rating'=>4.8,'mentees'=>85,'bio'=>'CTO Investree dan serial entrepreneur. Passion membantu founder startup validasi ide dan bangun tech team solid.','experience'=>[['role'=>'CTO','company'=>'Investree','period'=>'2020 – Kini','desc'=>'Platform fintech lending, 500K+ borrower.'],['role'=>'Co-Founder & CTO','company'=>'TechStartup (Exit $5M)','period'=>'2016 – 2020','desc'=>'Bangun dan exit SaaS startup.']],'education'=>[['institution'=>'Stanford University','degree'=>'MS Computer Science','year'=>'2012–2014','gpa'=>'3.88']],'achievements'=>[['icon'=>'🏆','title'=>'Startup Indonesia Award - Best CTO','issuer'=>'BUMN','year'=>'2023']],'programs'=>[['title'=>'Startup Tech Validation','price'=>'Rp 400.000','desc'=>'Validasi tech stack startup sebelum pitching ke VC.','duration'=>'60 menit','format'=>'Video Call','enrolled'=>65],['title'=>'From Zero to MVP','price'=>'Rp 2.000.000','desc'=>'6 sesi: ideation → tech stack → deploy MVP pertama Anda.','duration'=>'6x 90 menit','format'=>'Cohort + Hands-on','enrolled'=>20]],'testimonials'=>[['name'=>'Fajar Nugroho','role'=>'Founder PasarKu','stars'=>5,'comment'=>'MVP kami jadi dalam 3 bulan berkat Reza!'],['name'=>'Maya Sari','role'=>'CEO EduTech Startup','stars'=>4,'comment'=>'Sesi validasinya sangat membantu saat pitching investor.']]],
            ['name'=>'Dr. Amelia Hartono','email'=>'amelia@blitarhub.com','company'=>'Universitas Indonesia','expertise'=>'Academic & Research Mentor','location'=>'Depok, Jawa Barat','rating'=>4.9,'mentees'=>95,'bio'=>'Dosen UI sekaligus peneliti aktif. Telah membimbing 40+ mahasiswa S2/S3 dan membantu publikasi di jurnal Q1.','experience'=>[['role'=>'Associate Professor','company'=>'Universitas Indonesia','period'=>'2015 – Kini','desc'=>'Mengajar Machine Learning dan Data Mining.'],['role'=>'Postdoctoral Researcher','company'=>'MIT (USA)','period'=>'2013 – 2015','desc'=>'Riset natural language processing.']],'education'=>[['institution'=>'MIT','degree'=>'PhD Computer Science','year'=>'2009–2013','gpa'=>'4.0']],'achievements'=>[['icon'=>'🏆','title'=>'Best Paper Award ICML 2022','issuer'=>'ICML','year'=>'2022'],['icon'=>'📜','title'=>'Guru Besar Termuda UI 2023','issuer'=>'Universitas Indonesia','year'=>'2023']],'programs'=>[['title'=>'Academic Writing & Publikasi','price'=>'Rp 300.000','desc'=>'Bimbingan menulis paper untuk jurnal internasional (Scopus/Q1).','duration'=>'60 menit','format'=>'Video Call','enrolled'=>72],['title'=>'Research Methodology','price'=>'Rp 450.000','desc'=>'Dari perumusan masalah research hingga analisis data.','duration'=>'90 menit','format'=>'Video Call + Review','enrolled'=>38]],'testimonials'=>[['name'=>'Budi (Mahasiswa S2)','role'=>'Mahasiswa S2 Ilmu Komputer UI','stars'=>5,'comment'=>'Paper saya diterima di jurnal Q1 berkat bimbingan Dr. Amelia!'],['name'=>'Fitri Ramadhani','role'=>'Dosen Politeknik','stars'=>5,'comment'=>'Metodologinya sangat sistematis dan mudah dipahami.']]],
            ['name'=>'Santoso Budiman','email'=>'santoso@blitarhub.com','company'=>'McKinsey & Company','expertise'=>'Business Strategy Consultant','location'=>'Jakarta, Indonesia','rating'=>4.9,'mentees'=>60,'bio'=>'Senior Consultant di McKinsey dengan fokus digital transformation dan business strategy untuk perusahaan Fortune 500 Asia.','experience'=>[['role'=>'Senior Consultant','company'=>'McKinsey & Company','period'=>'2018 – Kini','desc'=>'Konsultasi untuk 20+ perusahaan BUMN dan swasta.'],['role'=>'Business Analyst','company'=>'Boston Consulting Group','period'=>'2015 – 2018','desc'=>'Analisis pasar dan strategi ekspansi bisnis.']],'education'=>[['institution'=>'Harvard Business School','degree'=>'MBA','year'=>'2013–2015','gpa'=>'3.95']],'achievements'=>[['icon'=>'🏆','title'=>'Top 10 Consultants Asia-Pacific','issuer'=>'Consulting Magazine','year'=>'2023'],['icon'=>'📜','title'=>'CFA Level III','issuer'=>'CFA Institute','year'=>'2017']],'programs'=>[['title'=>'Business Plan Review','price'=>'Rp 600.000','desc'=>'Review dan perbaikan business plan untuk startup atau UMKM.','duration'=>'90 menit','format'=>'Video Call + Dokumen','enrolled'=>45],['title'=>'Strategy for Entrepreneurs','price'=>'Rp 1.000.000','desc'=>'Modul strategi bisnis 3 sesi untuk founder yang ingin scale.','duration'=>'3x 90 menit','format'=>'Cohort-based','enrolled'=>25]],'testimonials'=>[['name'=>'CEO Startup B2B','role'=>'CEO B2B SaaS','stars'=>5,'comment'=>'Santoso membantu kami pivot strategy dan akhirnya dapat Series A!'],['name'=>'Pengusaha Kuliner','role'=>'Owner Resto Chain','stars'=>5,'comment'=>'Business plan kami jadi jauh lebih solid setelah direview.']]],
            ['name'=>'Yuni Kartika','email'=>'yuni@blitarhub.com','company'=>'Google','expertise'=>'UX Research Lead','location'=>'Singapore','rating'=>5.0,'mentees'=>45,'bio'=>'UX Research Lead di Google Asia Pacific. Membantu perusahaan memahami pengguna mereka secara mendalam melalui riset yang tepat sasaran.','experience'=>[['role'=>'UX Research Lead','company'=>'Google','period'=>'2020 – Kini','desc'=>'Memimpin riset untuk produk Google Maps Asia.'],['role'=>'Senior UX Researcher','company'=>'Facebook','period'=>'2017 – 2020','desc'=>'Riset pengguna untuk Facebook Marketplace SEA.']],'education'=>[['institution'=>'Carnegie Mellon University','degree'=>'MS Human-Computer Interaction','year'=>'2015–2017','gpa'=>'3.93']],'achievements'=>[['icon'=>'🏆','title'=>'CHI Best Paper Award','issuer'=>'ACM','year'=>'2023'],['icon'=>'📜','title'=>'Google Research Excellence Award','issuer'=>'Google','year'=>'2022']],'programs'=>[['title'=>'UX Research Fundamentals','price'=>'Rp 350.000','desc'=>'Cara melakukan user interview, usability testing, dan analisis data.','duration'=>'75 menit','format'=>'Video Call','enrolled'=>55],['title'=>'Research for Product Teams','price'=>'Rp 800.000','desc'=>'Workshop 2 sesi: embed research di agile product team.','duration'=>'2x 90 menit','format'=>'Workshop Online','enrolled'=>18]],'testimonials'=>[['name'=>'Ahsan PM','role'=>'Product Manager','stars'=>5,'comment'=>'Setelah sesi ini, kami jauh lebih user-centric dalam setiap keputusan produk.'],['name'=>'Diana Designer','role'=>'UX Designer','stars'=>5,'comment'=>'Riset yang tepat membuat desain saya jauh lebih impactful.']]],
        ];

        foreach ($mentors as $data) {
            $user = User::create([
                'name' => $data['name'],
                'email' => $data['email'],
                'password' => bcrypt('password'),
            ]);

            $mentor = Mentor::create([
                'user_id' => $user->id,
                'company' => $data['company'],
                'expertise' => $data['expertise'],
                'location' => $data['location'],
                'bio' => $data['bio'],
                'rating' => $data['rating'],
                'mentees_count' => $data['mentees'],
            ]);

            foreach ($data['experience'] as $i => $exp) {
                $mentor->experiences()->create(['role'=>$exp['role'],'company'=>$exp['company'],'period'=>$exp['period'],'description'=>$exp['desc'],'sort_order'=>$i]);
            }
            foreach ($data['education'] as $i => $edu) {
                $mentor->educations()->create(['institution'=>$edu['institution'],'degree'=>$edu['degree'],'year'=>$edu['year'],'gpa'=>$edu['gpa'],'sort_order'=>$i]);
            }
            foreach ($data['achievements'] as $i => $ach) {
                $mentor->achievements()->create(['icon'=>$ach['icon'],'title'=>$ach['title'],'issuer'=>$ach['issuer'],'year'=>$ach['year'],'sort_order'=>$i]);
            }
            foreach ($data['programs'] as $prog) {
                $mentor->programs()->create(['title'=>$prog['title'],'description'=>$prog['desc'],'price'=>$prog['price'],'duration'=>$prog['duration'],'format'=>$prog['format'],'enrolled'=>$prog['enrolled']]);
            }
            foreach ($data['testimonials'] as $t) {
                $mentor->testimonials()->create(['name'=>$t['name'],'role'=>$t['role'],'stars'=>$t['stars'],'comment'=>$t['comment']]);
            }
        }
    }
}
